# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dpentlan <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/01 11:49:44 by dpentlan          #+#    #+#              #
#    Updated: 2022/09/01 13:06:44 by dpentlan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = 

SRCS = 	ft_putchar.c\
		ft_swap.c\
		ft_putstr.c\
		ft_strlen.c\
		ft_strcmp.c

SRCS_FOLDER =	srcs/

HEADERS_FOLDER =	includes/

OBJS =	$(SRCS:.c=.o)

all:	$(OBJS)
		gcc -o yes $(OBJS)
